[env]
TERM = "screen-256color"

[font]
size = 13

[font.normal]
family = "VictorMono Nerd Font Mono"
style = "Regular"

[window]
opacity = 1
decorations = "none"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[general]
import = ["dracula.toml"]

[terminal.shell]
program = '/bin/zsh'
args = ["-l", "-c", "tmux a || tmux"]

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"
