[env]
TERM = "alacritty"

[font]
size = 13

[font.normal]
family = "VictorMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "VictorMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "VictorMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "VictorMono Nerd Font Mono"
style = "Bold Italic"

[window]
decorations = "none"
dynamic_padding = true
option_as_alt = "Both"

[window.padding]
x = 0
y = 0

[general]
import = ["dracula.toml"]

[terminal.shell]
program = '/bin/zsh'
args = ["-l", "-c", "tmux a || tmux"]

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"
